### ISSUE TITLE
TypeError: Encoder is not a constructor

### ISSUE THREAD

**Issue by ghost** [AlexMasterov/msgpuck.js#1]
Hi. I'm trying to use this but I get `TypeError: Encoder is not a constructor`

Code:

```javascript
const Encoder = require("msgpuck")
const test = new Encoder()
```

**Comment by AlexMasterov** [comment]
Hello,

Please see the [readme](https://github.com/AlexMasterov/msgpuck.js/tree/6dfd140302c75a50cdb0d9b23dbca299bfa979c8#encoding):
### Encoding
To encode values you can either use an instance of `Encoder`:
```javascript
const { Encoder } = require('msgpuck');
const encoder = new Encoder();

const binary = encoder.encode(127); 
```
`binary` is the _string_ type. Its a feature.
